"""add tariffs and holidays, add vehicle has_attachment

Revision ID: 3d8a191b05ae
Revises: 616adda9bdf1
Create Date: 2026-10-10 17:30:10.187684

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d8a191b05ae"
down_revision: str | Sequence[str] | None = "616adda9bdf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False, comment="Дата праздника."),
        sa.Column(
            "name",
            sa.String(length=200),
            nullable=False,
            comment="Название: Новый год, 8 марта, ...",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="active",
            nullable=False,
            comment="active / archived.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name="ck_holidays_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holidays_date"), "holidays", ["date"], unique=True)
    op.create_index(op.f("ix_holidays_status"), "holidays", ["status"], unique=False)
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "vehicle_type",
            sa.String(length=50),
            nullable=False,
            comment="Тип техники: excavator, dump_truck, manipulator, dropside.",
        ),
        sa.Column(
            "work_mode",
            sa.String(length=30),
            nullable=True,
            comment="Режим: regular (ковш), attachment (навесное), kmu (работа КМУ), delivery (доставка), haul (перевозка).",
        ),
        sa.Column(
            "unit",
            sa.String(length=20),
            nullable=False,
            comment="Единица: hour, ton, m3, trip, fixed.",
        ),
        sa.Column(
            "from_location_id",
            sa.Integer(),
            nullable=True,
            comment="Откуда (NULL = без привязки к маршруту).",
        ),
        sa.Column(
            "to_location_id",
            sa.Integer(),
            nullable=True,
            comment="Куда (NULL = без привязки к маршруту).",
        ),
        sa.Column(
            "material_id",
            sa.Integer(),
            nullable=True,
            comment="Конкретный материал (NULL = без материала / только доставка).",
        ),
        sa.Column(
            "material_type",
            sa.String(length=30),
            nullable=True,
            comment="Категория материала: inert, soil, construction_waste, msw.",
        ),
        sa.Column(
            "counterparty_id",
            sa.Integer(),
            nullable=True,
            comment="Клиент (NULL = для всех).",
        ),
        sa.Column(
            "applies_on",
            sa.String(length=20),
            server_default="any",
            nullable=False,
            comment="any, weekday, weekend, holiday.",
        ),
        sa.Column(
            "valid_from", sa.Date(), nullable=False, comment="С какой даты действует."
        ),
        sa.Column(
            "valid_to",
            sa.Date(),
            nullable=True,
            comment="По какую дату (NULL = бессрочно).",
        ),
        sa.Column(
            "value",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Цена за единицу. NULL = договорной (вводится вручную).",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Свободные заметки."),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="active",
            nullable=False,
            comment="active / archived.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name="ck_tariffs_status"
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from", name="ck_tariffs_dates"
        ),
        sa.CheckConstraint(
            "value IS NULL OR value > 0", name="ck_tariffs_value_positive"
        ),
        sa.ForeignKeyConstraint(
            ["counterparty_id"], ["counterparties.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"], ["locations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["material_id"], ["materials.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["to_location_id"], ["locations.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tariffs_applies_on"), "tariffs", ["applies_on"], unique=False
    )
    op.create_index(op.f("ix_tariffs_status"), "tariffs", ["status"], unique=False)
    op.create_index(op.f("ix_tariffs_unit"), "tariffs", ["unit"], unique=False)
    op.create_index(
        op.f("ix_tariffs_vehicle_type"), "tariffs", ["vehicle_type"], unique=False
    )
    op.create_index(
        op.f("ix_tariffs_work_mode"), "tariffs", ["work_mode"], unique=False
    )
    op.add_column(
        "vehicles",
        sa.Column(
            "has_attachment",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Есть навесное оборудование (гидромолот, трамбовка, ямобур).",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicles", "has_attachment")
    op.drop_index(op.f("ix_tariffs_work_mode"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_vehicle_type"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_unit"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_status"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_applies_on"), table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_index(op.f("ix_holidays_status"), table_name="holidays")
    op.drop_index(op.f("ix_holidays_date"), table_name="holidays")
    op.drop_table("holidays")
    # ### end Alembic commands ###
