"""add drivers and driver_absences tables

Revision ID: 5562bbe34e21
Revises: f9a82578ee95
Create Date: 2026-10-03 01:23:45.644380

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5562bbe34e21'
down_revision: str | Sequence[str] | None = 'f9a82578ee95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Фамилия.'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Имя.'),
    sa.Column('middle_name', sa.String(length=100), nullable=True, comment='Отчество. Может отсутствовать.'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Телефон в формате +7ХХХХХХХХХХ. Хранится нормализованным.'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='Жизненный цикл: active, fired. Отпуска — в driver_absences.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Свободные заметки.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'fired')", name='ck_drivers_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_drivers_last_name'), 'drivers', ['last_name'], unique=False)
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_table('driver_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False, comment='Водитель, к которому относится отсутствие.'),
    sa.Column('absence_type', sa.String(length=20), nullable=False, comment='Тип: vacation, sick_leave, absenteeism, other.'),
    sa.Column('date_from', sa.Date(), nullable=False, comment='Дата начала отсутствия.'),
    sa.Column('date_to', sa.Date(), nullable=True, comment='Дата окончания. NULL — водитель ещё не вернулся.'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Комментарий: причина, детали.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("absence_type IN ('vacation', 'sick_leave', 'absenteeism', 'other')", name='ck_driver_absences_type'),
    sa.CheckConstraint('date_to IS NULL OR date_to >= date_from', name='ck_driver_absences_dates'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_absences_driver_id'), 'driver_absences', ['driver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_absences_driver_id'), table_name='driver_absences')
    op.drop_table('driver_absences')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_last_name'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
