"""add fuel consumption and mileage records

Revision ID: 616adda9bdf1
Revises: 6fbfcbd102ed
Create Date: 2026-10-08 16:37:18.517558

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "616adda9bdf1"
down_revision: str | Sequence[str] | None = "6fbfcbd102ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mileage_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False, comment="Машина."),
        sa.Column("record_date", sa.Date(), nullable=False, comment="Дата показания."),
        sa.Column(
            "mileage_km",
            sa.Integer(),
            nullable=False,
            comment="Показания одометра, км.",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            server_default="manual",
            nullable=False,
            comment="Источник: manual (водитель), trip (расчёт), gps (трекер).",
        ),
        sa.Column(
            "driver_id",
            sa.Integer(),
            nullable=True,
            comment="Кто ввёл (если водитель).",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Свободные заметки."),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'trip', 'gps')", name="ck_mileage_records_source"
        ),
        sa.CheckConstraint(
            "mileage_km >= 0", name="ck_mileage_records_mileage_non_negative"
        ),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mileage_records_record_date"),
        "mileage_records",
        ["record_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mileage_records_vehicle_id"),
        "mileage_records",
        ["vehicle_id"],
        unique=False,
    )
    op.add_column(
        "vehicles",
        sa.Column(
            "fuel_consumption_per_100km",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Расход л/100км. Для колёсной техники.",
        ),
    )
    op.add_column(
        "vehicles",
        sa.Column(
            "fuel_consumption_per_hour",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Расход л/час. Для спецтехники.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicles", "fuel_consumption_per_hour")
    op.drop_column("vehicles", "fuel_consumption_per_100km")
    op.drop_index(op.f("ix_mileage_records_vehicle_id"), table_name="mileage_records")
    op.drop_index(op.f("ix_mileage_records_record_date"), table_name="mileage_records")
    op.drop_table("mileage_records")
    # ### end Alembic commands ###
