"""add materials table

Revision ID: 691898e3f4ba
Revises: 5562bbe34e21
Create Date: 2026-10-06 10:58:02.470454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691898e3f4ba'
down_revision: Union[str, Sequence[str], None] = '5562bbe34e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название: Щебень 5-20, Газоблок D500, Дизель.'),
    sa.Column('material_type', sa.String(length=30), nullable=False, comment='Тип: inert, concrete, soil, construction_waste, msw, fuel, building_material, other.'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Единица измерения: ton, m3, piece, liter, pallet, bag, roll.'),
    sa.Column('is_bulk', sa.Boolean(), server_default='false', nullable=False, comment='Насыпной? True — тарификация по массе.'),
    sa.Column('density_kg_m3', sa.Integer(), nullable=True, comment='Плотность кг/м³. NULL — не задана.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Свободные заметки.'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='active / archived.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_materials_status'),
    sa.CheckConstraint('density_kg_m3 IS NULL OR density_kg_m3 > 0', name='ck_materials_density_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_material_type'), 'materials', ['material_type'], unique=False)
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=True)
    op.create_index(op.f('ix_materials_status'), 'materials', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_status'), table_name='materials')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_material_type'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
