"""add locations table

Revision ID: 6fbfcbd102ed
Revises: cf8013efbd1b
Create Date: 2026-10-08 13:01:04.141317

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fbfcbd102ed"
down_revision: str | Sequence[str] | None = "cf8013efbd1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=200),
            nullable=False,
            comment="Название: Карьер Первомайский, Объект на Ленина 5.",
        ),
        sa.Column(
            "location_type",
            sa.String(length=30),
            nullable=False,
            comment="Тип: base, quarry, rbu, dump, landfill, construction_site, warehouse, other.",
        ),
        sa.Column(
            "address",
            sa.String(length=500),
            nullable=True,
            comment="Адрес (свободный текст).",
        ),
        sa.Column(
            "latitude",
            sa.Numeric(precision=9, scale=6),
            nullable=True,
            comment="Широта. NULL — не задана.",
        ),
        sa.Column(
            "longitude",
            sa.Numeric(precision=9, scale=6),
            nullable=True,
            comment="Долгота. NULL — не задана.",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Свободные заметки."),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="active",
            nullable=False,
            comment="active / archived.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name="ck_locations_status"
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)",
            name="ck_locations_latitude",
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)",
            name="ck_locations_longitude",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_locations_location_type"), "locations", ["location_type"], unique=False
    )
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=True)
    op.create_index(op.f("ix_locations_status"), "locations", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_locations_status"), table_name="locations")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_index(op.f("ix_locations_location_type"), table_name="locations")
    op.drop_table("locations")
    # ### end Alembic commands ###
