"""add phone to users

Revision ID: c5e87c8b6c54
Revises: ccbbc0212d11
Create Date: 2026-09-29 17:18:07.401574

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5e87c8b6c54"
down_revision: str | Sequence[str] | None = "ccbbc0212d11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
