"""add counterparties table

Revision ID: cf8013efbd1b
Revises: 691898e3f4ba
Create Date: 2026-10-06 17:15:47.021186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8013efbd1b'
down_revision: Union[str, Sequence[str], None] = '691898e3f4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Название: ООО Кубань Капитал групп, РБУ Юг-Бетон.'),
    sa.Column('counterparty_type', sa.String(length=30), nullable=False, comment='Тип: rbu, client, fuel_station, service_station, leasing, contractor, supplier, other.'),
    sa.Column('inn', sa.String(length=12), nullable=True, comment='ИНН: 10 цифр (юрлицо) или 12 (ИП/физлицо).'),
    sa.Column('kpp', sa.String(length=9), nullable=True, comment='КПП: 9 цифр.'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Телефон в формате +7XXXXXXXXXX.'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email.'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Юридический адрес (свободный текст).'),
    sa.Column('contact_person', sa.String(length=200), nullable=True, comment='Контактное лицо: ФИО, должность.'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Свободные заметки.'),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False, comment='active / archived.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_counterparties_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_counterparty_type'), 'counterparties', ['counterparty_type'], unique=False)
    op.create_index(op.f('ix_counterparties_name'), 'counterparties', ['name'], unique=True)
    op.create_index(op.f('ix_counterparties_status'), 'counterparties', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparties_status'), table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_name'), table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_counterparty_type'), table_name='counterparties')
    op.drop_table('counterparties')
    # ### end Alembic commands ###
