"""add vehicles table

Revision ID: f9a82578ee95
Revises: c5e87c8b6c54
Create Date: 2026-10-02 00:52:49.245005

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9a82578ee95"
down_revision: str | Sequence[str] | None = "c5e87c8b6c54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "plate_number",
            sa.String(length=20),
            nullable=False,
            comment="Госномер. Хранится в верхнем регистре без пробелов.",
        ),
        sa.Column(
            "vin",
            sa.String(length=17),
            nullable=False,
            comment="VIN. Хранится в верхнем регистре без пробелов.",
        ),
        sa.Column("brand", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False, comment="Год выпуска."),
        sa.Column(
            "vehicle_type",
            sa.String(length=50),
            nullable=False,
            comment="Тип техники: dump_truck, manipulator, excavator, dropside, ...",
        ),
        sa.Column(
            "capacity_kg", sa.Integer(), nullable=True, comment="Грузоподъемность в кг."
        ),
        sa.Column(
            "volume_m3",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Объем кузова в м³.",
        ),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Свободные заметки."),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'repair', 'sold')", name="ck_vehicles_status"
        ),
        sa.CheckConstraint(
            "vehicle_type IN ('dump_truck', 'manipulator', 'excavator', 'dropside', 'other')",
            name="ck_vehicles_type",
        ),
        sa.CheckConstraint(
            "capacity_kg IS NULL OR capacity_kg > 0",
            name="ck_vehicles_capacity_positive",
        ),
        sa.CheckConstraint(
            "volume_m3 IS NULL OR volume_m3 > 0", name="ck_vehicles_volume_positive"
        ),
        sa.CheckConstraint("year >= 2010 AND year <= 2150", name="ck_vehicles_year"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vin"),
    )
    op.create_index(
        op.f("ix_vehicles_plate_number"), "vehicles", ["plate_number"], unique=True
    )
    op.create_index(op.f("ix_vehicles_status"), "vehicles", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vehicles_status"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_plate_number"), table_name="vehicles")
    op.drop_table("vehicles")
    # ### end Alembic commands ###
